import type { ISODateTime, Todo } from './types';

/** Checklist completion invariant (spec 2026-08-11 §2): for a todo with a
 *  NON-EMPTY checklist, `done === every item checked`, always. Whenever a
 *  flip happens, false->true stamps `completedAt = now` and true->false
 *  clears it -- identical semantics to the manual toggle, regardless of
 *  which function caused the flip. A todo without a checklist is returned
 *  as-is (its `done` is owned by setTodoDone / the manual toggle alone).
 *
 *  INV-5 consequence, deliberate: auto-completion produces `done: true`
 *  exactly like manual completion, so the todo stops rolling over and stays
 *  pinned to the day/month it completed in (applyRollover and carryOverTodos
 *  both skip `done` todos). See the interplay tests in checklist.test.ts. */
function reconcileDone(todo: Todo, now: ISODateTime): Todo {
  if (!todo.checklist || todo.checklist.length === 0) return todo;
  const allChecked = todo.checklist.every((i) => i.checked);
  if (allChecked === todo.done) return todo;
  return { ...todo, done: allChecked, completedAt: allChecked ? now : undefined };
}

/** Flip one item's `checked`, then reconcile `done`/`completedAt` per the
 *  invariant. Checking the last unchecked item completes the todo;
 *  unchecking any item of a done todo reopens it. */
export function toggleChecklistItem(todo: Todo, itemId: string, now: ISODateTime): Todo {
  if (!todo.checklist) return todo;
  const checklist = todo.checklist.map((i) => (i.id === itemId ? { ...i, checked: !i.checked } : i));
  return reconcileDone({ ...todo, checklist }, now);
}

/** Append the item unchecked, then reconcile: adding an item to a completed
 *  todo REOPENS it (the invariant wins). The id is generated by the caller
 *  (the store, same crypto.randomUUID() mechanism as addTodo). Text
 *  trimming/rejection is the store's job, not the domain's. */
export function addChecklistItem(
  todo: Todo,
  item: { id: string; text: string },
  now: ISODateTime,
): Todo {
  const checklist = [...(todo.checklist ?? []), { id: item.id, text: item.text, checked: false }];
  return reconcileDone({ ...todo, checklist }, now);
}

/** Remove the item, then reconcile: removing the last UNCHECKED item while
 *  the rest are checked auto-completes the todo. Removing the final
 *  remaining item normalizes `checklist` back to undefined (never an empty
 *  array) and leaves `done` exactly as it was. */
export function removeChecklistItem(todo: Todo, itemId: string, now: ISODateTime): Todo {
  if (!todo.checklist) return todo;
  const remaining = todo.checklist.filter((i) => i.id !== itemId);
  if (remaining.length === 0) {
    const { checklist: _removed, ...rest } = todo;
    return rest;
  }
  return reconcileDone({ ...todo, checklist: remaining }, now);
}

/** The parent toggle. Sets `done` (stamping completedAt on false->true,
 *  preserving it when already done, clearing it on ->false) and, if a
 *  checklist exists, sets EVERY item's `checked` to match -- this is what
 *  makes "check the parent -> check all sub-items" and its mirror hold. */
export function setTodoDone(todo: Todo, done: boolean, now: ISODateTime): Todo {
  const completedAt = done ? (todo.done ? todo.completedAt : now) : undefined;
  const next: Todo = { ...todo, done, completedAt };
  if (todo.checklist) {
    next.checklist = todo.checklist.map((i) => (i.checked === done ? i : { ...i, checked: done }));
  }
  return next;
}
