export type ISODate = string;      // "YYYY-MM-DD", local calendar date. Sorts lexicographically.
export type ISODateTime = string;  // full ISO 8601 UTC (toISOString) — timestamps only
export type LocalDateTime = string;// "YYYY-MM-DDTHH:mm", no zone — reminders ("9am my time")

export type Priority = 'high' | 'medium' | 'low';
export type NoteCategory = 'blocker' | 'info';

export interface ChecklistItem {
  id: string;                 // crypto.randomUUID(), generated by the STORE
                              // (never the domain) so domain stays deterministic
  text: string;
  checked: boolean;
}

export interface Todo {
  id: string;                 // crypto.randomUUID()
  fortnightId: string;
  title: string;
  description?: string;
  priority: Priority;
  scheduledDay: ISODate;      // must be one of its fortnight's days
  done: boolean;
  completedAt?: ISODateTime;
  createdAt: ISODateTime;     // never changes across rollover/carry-over
  rolledOver: boolean;        // set when auto-moved off a past day; cleared if user reschedules
  reminderAt?: LocalDateTime;
  // Optional: absent (undefined) means "no checklist". NEVER an empty array
  // -- src/domain/checklist.ts normalizes [] back to undefined, because an
  // empty array would make the completion invariant (done === every item
  // checked) vacuously true. No schema bump needed -- same precedent as
  // Note.rolledOver: validatePersistedState never inspects todo internals,
  // only that `todos` is an object (INV-6 is for top-level PersistedState
  // fields, not nested value types).
  checklist?: ChecklistItem[];
}

export interface Note {
  id: string;
  fortnightId: string;
  day: ISODate;
  category: NoteCategory;
  text: string;
  resolved: boolean;          // only meaningful for 'blocker'; always false for 'info'
  createdAt: ISODateTime;
  // Optional: absent (undefined) means false. No schema bump needed -- see
  // exportImport.ts's validatePersistedState, which never inspects note
  // internals, only that `notes` is an object (INV-6 is for top-level
  // PersistedState fields, not nested value types).
  rolledOver?: boolean;
}

export interface Fortnight {
  id: string;
  startDay: ISODate;          // first workday of the period
  days: ISODate[];            // workdays of the period, ascending — a calendar
                               // month since schema v3; legacy 10-day
                               // fortnights persist unmigrated in history
  createdAt: ISODateTime;
}

export interface PomodoroSettings {
  workMinutes: number;
  breakMinutes: number;
  longBreakMinutes: number;
}

export interface PersistedState {
  schemaVersion: number;
  fortnights: Fortnight[];            // last = active; bounded by the 3-month
                                      // retention window (pruneToRetention runs
                                      // at month generation). Append-order --
                                      // sort by days[0] for display.
  activeFortnightId: string | null;
  todos: Record<string, Todo>;
  notes: Record<string, Note>;
  lastRolloverDay: ISODate | null;    // last local day rollover ran (idempotency)
  pomodoroSettings: PomodoroSettings; // added in schema v2 (defaults filled by migration)
}

// Store = PersistedState + ephemeral UI state (NOT persisted):
// viewedFortnightId, selectedDay, modal flags
